baseurl = "https://bradleycarey.com"
title = "bradleycarey.com"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
pagination.pagerSize = 20
googleAnalytics = "G-EPD3KTTXVQ"
enableRobotsTXT = true
enableGitInfo = true

[params]
author = "Bradley Carey"
description = "Bradley Carey's personal website, featuring articles and resources on software engineering, web development, and more."
keywords = "blog,programming,software engineering,web development,technology,productivity,consulting,angular"
info = "Principal Software Engineer, Tech Lead"
avatarurl = "images/bird.png"
faviconSVG = "images/bird.svg"
favicon_32 = "images/favicon.png"
favicon_16 = "images/favicon.png"
dateformat = "Jan 2, 2006"
customSCSS = ["custom.scss"]
since = "2012"
colorScheme = "auto"
recentPostCount = "5"
commit = "https://github.com/avianbc/blog/tree/"

[params.giscus] # https://giscus.app
repo = "avianbc/blog"
repoID = "MDEwOlJlcG9zaXRvcnkxODc5Mjk5MTc="
category = "Announcements"
categoryID = "DIC_kwDOCzOVPc4C0LX"
mapping = "pathname"
term = ""
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
theme = "light"
lang = "en"
loading = ""

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/avianbc/"
[[params.social]]
name = "Stack Overflow"
icon = "fa fa-stack-overflow"
weight = 2
url = "https://stackoverflow.com/users/636942"
[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 3
url = "https://www.linkedin.com/in/bradley-carey-83ba3554/"
[[params.social]]
name = "RSS"
icon = "fa fa-rss"
weight = 4
url = "https://bradleycarey.com/index.xml"
rel = "alternate"
type = "application/rss+xml"
[[params.social]]
name = "Sitemap"
icon = "fa fa-sitemap"
weight = 5
url = "https://bradleycarey.com/sitemap.xml"
rel = "alternate"
type = "application/rss+xml"

[[menu.main]]
name = "Blog"
weight = 1
url  = "posts/"
[[menu.main]]
name = "Consulting"
weight = 2
url = "consulting/"
[[menu.main]]
name = "About"
weight = 3
url = "about/"

[markup]
[markup.highlight]
noClasses = false
tabWidth = 2

[markup.goldmark.renderer]
unsafe = true # Allow HTML in md files
